sudo: false

language: go

git:
  depth: 1

install: 
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.54.0

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
      branch: master
  local_dir: public
  repo: hurryking/hurryking.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot
