baseURL = "http://www.v2end.com"
languageCode = "zh-CN"
title = "胡言乱语"

summaryLength=50

github="https://github.com/hurryking"

theme = "jeffprod"

disqusShortname = "hu-yan-luan-yu"

[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    archive = "archives"
