baseURL = "http://v2end.com/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
