baseURL = "https://hurryking.github.io/"
languageCode = "zh-CN"
title = "胡言乱语"
author = "Mr King"

summaryLength=50

github="https://github.com/hurryking"

theme = "jeffprod"

disqusShortname = "hu-yan-luan-yu"

[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    archive = "archives"
