baseURL = "https://hurryking.github.io/"
languageCode = "zh-CN"
title = "胡言乱语"

github="https://github.com/hurryking"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
