baseURL = "http://hurryking.github.io/"
languageCode = "zh-CN"
title = "My New Hugo Site"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
